### ISSUE TITLE
Error on npm install - decompress not found

### ISSUE THREAD

**Issue by hades200082** [WeAreAthlon/frontend-webpack-boilerplate#6] opened 2019-05-25 11:44 UTC
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/decompress/-/decompress-4.2.2.tgz
npm ERR! 404
npm ERR! 404  'decompress@4.2.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'LeeConlin.Web.Html'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lee20\AppData\Roaming\npm-cache\_logs\2019-05-25T11_43_37_808Z-debug.log
```

**Comment by pnikolov** [comment] 2019-05-28 08:23
It seems that the reported error cannot be reproduce. Maybe it was due to temporary outage of on npmjs.org?
Can you try again with clean install `npm ci` and the latest [Release 2.6.1](https://github.com/WeAreAthlon/frontend-webpack-boilerplate/releases/tag/v2.6.1)?

**Comment by pnikolov** [comment] 2019-06-05 15:19
As there is no any additional feedback I am closing this issue.

**Closed by pnikolov** 2019-06-05 15:19 UTC
Labels: not reproducible
